### ISSUE TITLE
Adding FAQs

### ISSUE THREAD

**Issue by AswaniBolisetti** [Vimall03/Alimento#101] opened 2024-10-13 15:25 UTC
@Vimall03 
I would like to add FAQs
could you please assign me this

**Comment by Vimall03** [comment] 2024-10-13 17:22
@AswaniBolisetti This issue is fixed in #99 
Closing this as Duplicate of #79

**Closed by Vimall03** 2024-10-13 17:22 UTC

**Comment by AswaniBolisetti** [comment] 2024-10-13 17:36
@Vimall03 I mean i want to add a button - load more FAQs, by clicking on it, few more faqs will be displayed
