### ISSUE TITLE
Adding styling and improvements in footer

### ISSUE THREAD

**Issue by aditiverma-21** [Vimall03/Alimento#5] opened 2024-10-01 17:47 UTC
![image](https://github.com/user-attachments/assets/7d83e9e8-6ef4-494a-9768-f306a90a4d71)
the logo doesn't appear quiet right because of the color palatte. Required few styling changes

**Comment by Vimall03** [comment] 2024-10-01 19:02
- Duplicate of issue #2

**Closed by Vimall03** 2024-10-01 19:02 UTC
