### ISSUE TITLE
[FEAT] Adding feature cards with effects

### ISSUE THREAD

**Issue by aditiverma-21** [Vimall03/Alimento#25] opened 2024-10-03 08:21 UTC
Feature Cards Layout: Each feature card will display a title, description, icon/image, and a CTA (Call to Action) button.
Hover Effects: Implement hover effects like shadow lifting, color changes, or subtle animations to make cards interactive.
Responsive Design: Ensure the feature cards are responsive for desktop and mobile views.
Transitions: Smooth transitions between hover and non-hover states for a seamless experience.

**Comment by Vimall03** [comment] 2024-10-03 15:54
Hey @aditiverma-21, This seems like a duplicate of #2

I have already assigned you issue #2 with level-3 label.

**Closed** 2024-10-03 15:55 UTC
Labels: hacktoberfest-accepted, gssoc-ext

**Comment by aditiverma-21** [comment] 2024-10-03 19:15
Okay no worries
